server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh   #payment_routh  路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001    #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
#        filters:
#          - AddRequestParameter=X-Request-Id,1024  #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
        predicates:
        - Path=/payment/get/**        #断言  路径相匹配的进行路由
      - id: payment_routh2
        #uri: http://localhost:8011
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进EurekaServer中 默认为true
    register-with-eureka: true
      #是否从Eureka Server抓取已有的注册信息，默认为true  单节点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka