server:
  port: 7001

eureka:
  instance:
    #hostname: localhost  #eureka服务端实例名称
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
#  server:
#    #关闭自我保护机制，保证不可用服务被及时剔除
#    enable-self-preservation: false
 #   eviction-interval-timer-in-ms: 2000
