server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer中 默认为true
    register-with-eureka: false
    #是否从Eureka Server抓取已有的注册信息，默认为true  单节点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版
      #defaultZone: http://localhost:7001/eureka

#用于服务降级 在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    enabled: true  #在feign中开启hystrix